sudo: required
before_install:
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io
  - docker version
  - docker run hello-world
install:
  - docker swarm init
  - docker service create --name registry --publish published=5000,target=5000 registry:2
  - sleep 5
  - curl http://localhost:5000/v2/
  - docker-compose build
  - docker-compose push
  - docker stack deploy -c docker-compose.yml mystack
  - sleep 5
  - docker stack ls
  - docker stack ps mystack
  - docker stack services mystack
  - sleep 25
script:
  - files/test_ukpostcode.sh
after_script:
  - docker stack rm mystack
