sudo: required
before_install:
  - apt-get remove docker docker-engine docker.io containerd runc
  - apt-get update
  - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install docker-ce docker-ce-cli containerd.io
  - docker version
  - docker-compose version
  - docker run hello-world
install:
  - docker-compose up -d
  - docker-compose ps
script:
  - files/test_ukpostcode.sh
after_script:
  - docker-compose down -v
