---
  version: "3"
  services:

    flask:
        build:
          dockerfile: './custom_nginx'
          context: '.'
        image: dockercompose_flask
        environment:
            - FLASK_APP=/usr/src/app/project/app.py
        command: flask run --host=0.0.0.0
        ports:
          - 5000:5000
        networks:
          - demo_app
        deploy:
          replicas: 3
    web:
      build:
        dockerfile: './custom_nginx'
        context: '.'
      image: dockercompose_web
      ports:
        - 8080:80
      volumes:
        - web_vol:/usr/share/nginx/html
      networks:
        - demo_app
      command: nginx -g 'daemon off;'
      restart: always
      depends_on:
        - db
        - flask
      deploy:
        replicas: 3
    db:
      build:
        dockerfile: './custom_mariadb'
        context: '.'
      image: dockercompose_db
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ukpostcodes
        MYSQL_USER: postcodes
        MYSQL_PASSWORD: secret
      ports:
        - 3306:3306
      #volumes:
      #  - mysql_vol:/var/lib/mysql
      networks:
        - demo_app
      restart: always
      deploy:
        replicas: 3

  networks:
    demo_app:

  volumes:
    web_vol:
    mysql_vol:
